const palette = {
  obsidian: "#0F1117",
  navy: "#1A1F2E",
  navyLight: "#242A3D",
  coral: "#FF6B35",
  coralDim: "#CC5529",
  teal: "#4ECDC4",
  sky: "#45B7D1",
  gold: "#F7C948",
  mint: "#6BCB77",
  lavender: "#8B7CF6",
  white: "#FFFFFF",
  offWhite: "#E8EAF0",
  muted: "#8B90A0",
  border: "#2E3450",
  error: "#FF4757",
};

export default {
  light: {
    text: palette.obsidian,
    background: "#F0F2F8",
    card: "#FFFFFF",
    cardAlt: "#E8EAF0",
    primary: palette.coral,
    secondary: palette.teal,
    accent: palette.sky,
    muted: "#6B7280",
    border: "#E0E3EC",
    tint: palette.coral,
    tabIconDefault: "#9CA3AF",
    tabIconSelected: palette.coral,
    error: palette.error,
    gold: palette.gold,
    mint: palette.mint,
    lavender: palette.lavender,
  },
  dark: {
    text: palette.white,
    background: palette.obsidian,
    card: palette.navy,
    cardAlt: palette.navyLight,
    primary: palette.coral,
    secondary: palette.teal,
    accent: palette.sky,
    muted: palette.muted,
    border: palette.border,
    tint: palette.coral,
    tabIconDefault: palette.muted,
    tabIconSelected: palette.coral,
    error: palette.error,
    gold: palette.gold,
    mint: palette.mint,
    lavender: palette.lavender,
  },
};
